import type { Metadata } from "next";
import "./globals.css";
import "../styles/style.scss"
import 'react-phone-input-2/lib/style.css'
import "react-datepicker/dist/react-datepicker.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
