"use client"

import "./globals.css";
import "../styles/style.scss"
import 'react-phone-input-2/lib/style.css'
import "react-datepicker/dist/react-datepicker.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import Head from "next/head";

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Provider store={store}>
        <body>
          {children}
        </body>
      </Provider>
    </>
  );
}

export default RootLayout
